name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

      - name: Deploy to droplet via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
            set -e
            echo "Navigating to app directory..."
            cd ~/workout-log-app
            echo "Pulling latest changes..."
            git pull origin master
            echo "Stopping containers..."
            docker compose down
            echo "Building containers..."
            docker compose build
            echo "Starting containers..."
            docker compose up -d
            echo "Deployment complete. Containers status:"
            docker compose ps
          EOF
